### ISSUE TITLE
Activate virtual environment

### ISSUE THREAD

**Issue by abdulrahim-ramadan** [abdulrahim-ramadan/aActivate-virtual-environment#1]
Check Tutorial tab to know how to to solve.

The included code stub will read an integer, n, from STDIN.

Without using any string methods, try to print the following:
123...n

Note that "" represents the consecutive values in between.

Example
n=5
Print the string .

Input Format

The first line contains an integer .

Constraints
1<n<150

Output Format

Print the list of integers from 1 through n as a string, without spaces.

Sample Input 0

3
Sample Output 0

123

**Comment by AbdullahBakir97** [comment]
# Navigate to the project directory
cd your_project_directory

# Create a virtual environment (if not created)
python -m venv venv

# Activate the virtual environment
.\venv\Scripts\Activate
